//Task 23;
var car = "sabaru";
console.log("is car ==`subaru` ? predict true");
console.log(car == "subaru");
console.log("is car != honda city ? true ");
console.log(car != "honda city");
console.log("is car ==`sabaru`? predict false");
console.log(car == "sabaru");
console.log("is car == `sabaru`? predict false");
console.log(car == "sabaru");
console.log("is car == `SABARU`? predict false");
console.log(car == "SABARU");
console.log("is car.length == 8? predict true");
console.log(car.length == 8);
console.log("is car.length != 12? predict true");
console.log(car.length != 12);
console.log("is 8 > 15 ? predict false");
console.log(8 > 15);
console.log("is 5 <= 3 ? predict false");
console.log(5 > 3);
console.log("is 8 > 12 ? predict false");
console.log(8 > 12);
console.log("is 8 >= 12 ? predict false");
console.log(8 >= 12);
console.log("is car == `sabaru` && car.length == 8? predict false ");
console.log(car == "sabaru" && car.length == 8);
